bind = $mainMod, Q, exec, $terminal

# This makes the browser open on the designated workspace when pressing MOD+B, but only if it doesn't already exist. In either case, we switch to that workspace
bind = $mainMod, B, exec, python ~/.config/hypr/modules/keybindings/scripts/browser.py $browser 11

# This just starts firefox, no matter where we are
bind = $mainMod SHIFT, B, exec, $browser

### Godot
bind = $mainMod, G, exec, godot --display-driver wayland

### Screenshot using hyprshot (grim and slurp, mostly)
bind = SHIFT, PRINT, exec, hyprshot -m region --clipboard-only
