bind = $mainMod, Q, exec, $terminal

# This makes the browser open on the designated workspace when pressing MOD+B, but only if it doesn't already exist. In either case, we switch to that workspace
bind = $mainMod, B, exec, python ~/.config/hypr/modules/keybindings/scripts/browser.py $browser 11

# This just starts firefox, no matter where we are
bind = $mainMod SHIFT, B, exec, $browser

