[window]
padding = { x = 6, y = 3 }
dynamic_padding = true
opacity = 0.9

[font]
normal.family = "JetbrainsMono NFM"
bold.family = "JetbrainsMono NFM"
italic.family = "JetbrainsMono NFM"
bold_italic.family = "JetbrainsMono NFM"
size = 12
