bind = SUPER, V, exec, $terminal --class clipse -e 'clipse'
bind = SUPER, V, submap, clipse

submap = clipse
bind = , RETURN, pass, class:clipse
bind = , RETURN, focuscurrentorlast, 
bind = , RETURN, exec, sleep 0.01 && ~/.config/hypr/modules/submaps/scripts/clipse-auto-paste.sh


bind = , escape, pass, class:clipse
bind = , Q, pass, class:clipse

bind = , escape, submap, reset
bind = , Q, submap, reset
bind = , RETURN, submap, reset

submap = reset

