### Move Window through tiling

bind = $mainMod ALT, S, submap, moveWindow

submap = moveWindow
bind = , escape, submap, reset

bind = , A, movewindow, l
bind = , D, movewindow, r
bind = , W, movewindow, u
bind = , S, movewindow, d

submap = reset
