### Move Window through tiling

bind = $mainMod ALT, S, submap, moveWindow

submap = moveWindow
bind = , escape, submap, reset

bind = $mainMod, left, movewindow, l
bind = $mainMod, right, movewindow, r
bind = $mainMod, up, movewindow, u
bind = $mainMod, down, movewindow, d

submap = reset
