### Refresh various programs

bind = $mainMod ALT, K, submap, refresh

submap = refresh
bind = , escape, submap, reset

bind = $mainMod, W, exec, $SAUCE_PATH/submaps/scripts/refresh.waybar.sh
bind = $mainMod ALT, W, exec, $SAUCE_PATH/submaps/scripts/refresh.waybar.sh 1

submap = reset
