# Setting the binding to activate the resize submap
bind = $mainMod ALT, R, submap, resize

# Defining the submap keybindings
submap = resize

binde = , A, resizeactive, -10 0
binde = , W, resizeactive, 0 -10
binde = , D, resizeactive, 10 0
binde = , S, resizeactive, 0 10

# Setting binding to deactivate the submap. Needs to be here, since the submap overwrites the global bindings
bind = , escape, submap, reset

# End Submap
submap = reset
